### ISSUE TITLE
Option to skip certain file

### ISSUE THREAD

**Issue by zuffik** [atlassian-labs/babel-plugin-storybook-csf-title#4]
I am a little confused as the plugin is trying to load all my files (not only stories), which obviously leads to errors being thrown (eg. _TypeError: Property init of VariableDeclarator expected node to be of a type ["Expression"] but instead got "FunctionDeclaration"_. This can be possible way to achieve the skip: if `toTitle` returns undefined (or any falsy expression) the file should be completely excluded.

**Comment by obweger** [comment]
Hi @zuffik - sorry just seeing this - let me have a closer look later today. In general, I'm typically handling it in my storybook webpack config as follows:

```js
config.module.rules.push(
        {
            test: /\.(ts|tsx)$/,
            loader: 'babel-loader',
            options: {
                presets: [['react-app', { flow: false, typescript: true }]],
                plugins: [
                    ['babel-plugin-storybook-csf-title', false],
                ],
                overrides: [{
                    include: /\/examples\.(ts|tsx)$/,
                    plugins: [
                        ['babel-plugin-storybook-csf-title', { toTitle }]
                    ]
                }]
            },
        },
    );
```

... so the plugin is off by default, and then only enabled for files that match the `examples` pattern  (which is the convention I use for my stories - you can use whatever you want).

Let me know if this helps.

**Comment by zuffik** [comment]
This was helpful, although it's confusing that it must be written twice.
Thank you anyway :)

**Comment by obweger** [comment]
Thx @zuffik! I updated the readme accordingly!
