### ISSUE TITLE
Option to disable default export insertion

### ISSUE THREAD

**Issue by brophdawg11** [atlassian-labs/babel-plugin-storybook-csf-title#6]
I was wondering if you would be open to adding an option to the plugin to disable the insertion of a default export if one does not exist.  We have a mix of CSF, MDX, and MDX+CSF stories in our storybook, and at the moment we're applying this plugin to any `*.stories.csf.js` files.

However, the storybook recommendation when you want to import a CSF file into an MDX file, and then _not_ have the CSF file be a story on it's own - is to remove the default export:

  https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs

When using this plugin, that approach no longer works as the plugin adds it back in.  Could we add an option such as `skipDefaultExportAddition: true` to allow better usage in the MDX+CSF scenario?  I'd be happy to open a PR if so

**Comment by mi6gan** [comment]
@brophdawg11
You may use https://github.com/atlassian-labs/babel-plugin-storybook-csf-title/pull/8

To remove default exports just set `renameDefaultExportsTo: false`

**Comment by obweger** [comment]
Hi @brophdawg11, sorry I've been away from this project for a bit but picking it up again now. Just to clarify, what you want is that...

- if a default export exists, then the plugin should behave exactly as it does currently.
- if there is no default export, then the plugin shouldn't do anything and leave the file untouched.

Is that correct?
